version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EMR_DATABASE: ${EMR_DATABASE}
      EMR_DB_USER: ${EMR_DATABASE_USER}
      EMR_DB_PASSWORD: ${EMR_DATABASE_PASSWORD}
      DDE_DATABASE: ${DDE_DATABASE}
      DDE_DB_USER: ${DDE_DATABASE_USER}
      DDE_DB_PASSWORD: ${DDE_DATABASE_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - emdeck-network

  emr:
    build:
      context: ./emr
    environment:
      DB_HOST: mysql
      DB_DATABASE: ${EMR_DATABASE}
      DB_USER: ${EMR_DATABASE_USER}
      DB_PASSWORD: ${EMR_DATABASE_PASSWORD}
    depends_on:
      - mysql
    networks:
      - emdeck-network

  dde:
    build:
      context: ./dde
    environment:
      DB_HOST: mysql
      DB_DATABASE: ${DDE_DATABASE}
      DB_USER: ${DDE_DATABASE_USER}
      DB_PASSWORD: ${DDE_DATABASE_PASSWORD}
    depends_on:
      - mysql
    networks:
      - emdeck-network

  frontend:
    build:
      context: ./frontend
    depends_on:
      - emr
    networks:
      - emdeck-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    environment:
      - ADMIN_USERNAME=${PORTAINER_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${PORTAINER_ADMIN_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - ${DOCKER_NETWORK}

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    restart: always
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - emdeck-network

networks:
  emdeck-network:
    driver: bridge

volumes:
  mysql-data:
